# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - python-vp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create, start virtual environment and install dependencies
        run: |
          python -m venv vedantVirtualEnvironment
          source vedantVirtualEnvironment/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9F9C03D077CC4EBBB928A6DFF89B592E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9EFACEA4D9234CDFB0A6B853C34C2537 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9CB876F44AA74B939B89EA89C1596601 }}
      
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'python-vp'
          slot-name: 'Production'
          clean: true
          startup-command: './startup.sh'

      - name: 'Set App Settings'
        run: |
          az webapp config appsettings set \
            --name python-vp \
            --resource-group TempRG \
            --settings \
              PORT=8000 \
              WEBSITE_HTTPLOGGING_RETENTION_DAYS=5 \
              SCM_DO_BUILD_DURING_DEPLOYMENT=0 \
              SIGNER_SECRET=VedantPatel \
              DEBUG=true